[project]
name = "cdk-wp-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aws-cdk-lib>=2.177.0",
    "constructs",
    "aws-cdk.aws-codestar-alpha>=2.0.0alpha1"
]
